IMAGE_BASE_URL: "/uploads"
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moim
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@gmail.com
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always # 실행 시 테이블 자동 생성 (운영 환경에서는 별도 관리 권장)
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 5
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - profile
              - email
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    com.moim.payment: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# KFTC API Configuration
kftc:
  client-id: 9a92d41c-5c0b-40eb-8099-414c81c5631d
  client-secret: da2ac591-8938-4281-a7f6-dd2414ec9bbf
  authorize-api-endpoint: https://testapi.openbanking.or.kr/oauth/2.0/authorize
  token-endpoint: https://testapi.openbanking.or.kr/oauth/2.0/token
  account-list-endpoint: https://testapi.openbanking.or.kr/v2.0/account/list
  user-info-endpoint: https://testapi.openbanking.or.kr/v2.0/user/me
  transaction-history-endpoint: https://testapi.openbanking.or.kr/v2.0/account/transaction_list/fin_num
  balance-inquiry-endpoint: https://testapi.openbanking.or.kr/v2.0/account/balance/fin_num
  inquiry-receive-endpoint: https://testapi.openbanking.or.kr/v2.0/inquiry/receive #수취조회
  transfer:
    deposit-endpoint: https://testapi.openbanking.or.kr/v2.0/transfer/deposit/fin_num
    withdraw-endpoint: https://testapi.openbanking.or.kr/v2.0/transfer/withdraw/fin_num